// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1AXKQdRpXZiSUhY9nbsK1KcvJiIuuik0',
    appId: '1:86388267041:web:27f52fdddc5d0cacd22b60',
    messagingSenderId: '86388267041',
    projectId: 'notas-45fe3',
    authDomain: 'notas-45fe3.firebaseapp.com',
    storageBucket: 'notas-45fe3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB749YXsENrKsmHEVu97D4KgWgFZfCug9c',
    appId: '1:86388267041:android:a7032a81f6fbcbefd22b60',
    messagingSenderId: '86388267041',
    projectId: 'notas-45fe3',
    storageBucket: 'notas-45fe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGxdNo9f6jxblwNwUZXafrh5OriH-c0Hs',
    appId: '1:86388267041:ios:6842a2574177336ad22b60',
    messagingSenderId: '86388267041',
    projectId: 'notas-45fe3',
    storageBucket: 'notas-45fe3.firebasestorage.app',
    iosBundleId: 'com.example.notas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGxdNo9f6jxblwNwUZXafrh5OriH-c0Hs',
    appId: '1:86388267041:ios:6842a2574177336ad22b60',
    messagingSenderId: '86388267041',
    projectId: 'notas-45fe3',
    storageBucket: 'notas-45fe3.firebasestorage.app',
    iosBundleId: 'com.example.notas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1AXKQdRpXZiSUhY9nbsK1KcvJiIuuik0',
    appId: '1:86388267041:web:9a3894c509aaad6cd22b60',
    messagingSenderId: '86388267041',
    projectId: 'notas-45fe3',
    authDomain: 'notas-45fe3.firebaseapp.com',
    storageBucket: 'notas-45fe3.firebasestorage.app',
  );

}