// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS7kOuvZU3v-Vs0NleMTDXKVNS0Uu99gk',
    appId: '1:1009576903639:web:75f552f9ecfbb52e2c0192',
    messagingSenderId: '1009576903639',
    projectId: 'notas-6f542',
    authDomain: 'notas-6f542.firebaseapp.com',
    storageBucket: 'notas-6f542.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4FMbucG4UqxUZ9X0FjQdQOV-xJUSd5UI',
    appId: '1:1009576903639:android:b0fb96874027a2fe2c0192',
    messagingSenderId: '1009576903639',
    projectId: 'notas-6f542',
    storageBucket: 'notas-6f542.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBP6U6jcpjac5p6JOonMrmZS1xwETbuTk',
    appId: '1:1009576903639:ios:132c696efafce1ba2c0192',
    messagingSenderId: '1009576903639',
    projectId: 'notas-6f542',
    storageBucket: 'notas-6f542.firebasestorage.app',
    iosBundleId: 'com.example.notas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBP6U6jcpjac5p6JOonMrmZS1xwETbuTk',
    appId: '1:1009576903639:ios:132c696efafce1ba2c0192',
    messagingSenderId: '1009576903639',
    projectId: 'notas-6f542',
    storageBucket: 'notas-6f542.firebasestorage.app',
    iosBundleId: 'com.example.notas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS7kOuvZU3v-Vs0NleMTDXKVNS0Uu99gk',
    appId: '1:1009576903639:web:7bd6179c13357e932c0192',
    messagingSenderId: '1009576903639',
    projectId: 'notas-6f542',
    authDomain: 'notas-6f542.firebaseapp.com',
    storageBucket: 'notas-6f542.firebasestorage.app',
  );
}
